### ISSUE TITLE
`cabal test` fails

### ISSUE THREAD

**Issue by andreasabel** [skogsbaer/HTF#109] opened 2021-11-16 08:44 UTC
`cabal test` fails:
```
[1 of 1] Compiling Main             ( tests/MiscTest.hs, /Users/abel/project/open-source/HTF/dist-newstyle/build/x86_64-osx/ghc-9.0.1/HTF-0.14.0.6/build/MiscTests/MiscTests-tmp/Main.o )
Linking /Users/abel/project/open-source/HTF/dist-newstyle/build/x86_64-osx/ghc-9.0.1/HTF-0.14.0.6/build/MiscTests/MiscTests ...
Preprocessing test suite 'TestHTF' for HTF-0.14.0.6..
Building test suite 'TestHTF' for HTF-0.14.0.6..
gfind: ‘/Users/abel/project/open-source/HTF/.stack-work/dist/x86_64-osx’: No such file or directory
TOP=/Users/abel/project/open-source/HTF
dist=.stack-work/dist/x86_64-osx/Cabal-3.0.1.0
bin=
No executable named htfpp found in /Users/abel/project/open-source/HTF/.stack-work/dist/x86_64-osx/Cabal-3.0.1.0. Aborting!
```
This can be maybe fixed by relying on`build-tool-depends: HTF:htfpp` in the tests rather than relying on the script `local-htfpp`: https://github.com/skogsbaer/HTF/blob/1d242b48dbde128df4dd8056bc68e0e2094485f0/scripts/local-htfpp

**Comment by skogsbaer** [comment] 2022-03-01 15:33
The problem is: `scripts/local-htfpp` uses `stack path` to find out the path to the htfpp executable build by the configuration defined in the stack.yaml file. Per default, this is currently ghc-8.8. Your invocation of `cabal test` uses ghc 9.0. 

I suggest you use `stack test` for running the tests. To use a ghc version different from the one in stack.yaml, you have to proceed like this:

```
export HTF_TEST_STACK_ARGS=--stack-yaml YOUR_FILE"
stack $HTF_TEST_STACK_ARGS test
```

This way, the `local-htfpp` script finds the correct htfpp executable.

Does this work for you?

**Comment by andreasabel** [comment] 2022-03-01 18:40
I was mainly interested in `cabal test` to function so that an auto-generated Haskell-CI would work out of the box.

**Comment by skogsbaer** [comment] 2022-03-05 16:54
Ok, so I'm closing the issue because we now have (handwritten) CI.

**Closed by skogsbaer** 2022-03-05 16:54 UTC
